function startScreen() {
  //Easy Mode button
  easyButton();
  //Hard Mode Button
  hardButton();
  gameInstructions();

}



//changes to state 2 when clicked and runs the easy level of the game.
function easyButton() {
  let leftSide = width / 2 - buttonWidth / 2;
  let topSide = height / 2 - buttonHeight / 2 - 80;
  let rightSide = leftSide + buttonWidth;
  let bottomSide = topSide + buttonHeight;

  fill(153, 153, 255);
  if (mouseX >= leftSide && mouseX <= rightSide && mouseY >= topSide && mouseY <= bottomSide) {
    fill(179, 102, 255);
    if (mouseIsPressed) {
      popSound.play();
      state = 2;
    }
  }

  noStroke();
  rect(leftSide, topSide, buttonWidth, buttonHeight);

  textStyle(BOLD);
  textSize(36);
  textAlign(CENTER, CENTER);
  fill(0);
  text("Easy Mode", leftSide + 0.5 * buttonWidth, topSide + 0.5 * buttonHeight);
}



//changes to state 3 when clicked and runs the hard level of the game.
function hardButton() {
  let leftSide = width / 2 - buttonWidth / 2;
  let topSide = height / 2 - buttonHeight / 2 + 80;
  let rightSide = leftSide + buttonWidth;
  let bottomSide = topSide + buttonHeight;

  fill(153, 153, 255);
  if (mouseX >= leftSide && mouseX <= rightSide && mouseY >= topSide && mouseY <= bottomSide) {
    fill(179, 102, 255);
    if (mouseIsPressed) {
      popSound.play();
      state = 3;
    }
  }

  noStroke();
  rect(leftSide, topSide, buttonWidth, buttonHeight);

  textStyle(BOLD);
  textSize(36);
  textAlign(CENTER, CENTER);
  fill(0);
  text("Hard Mode", leftSide + 0.5 * buttonWidth, topSide + 0.5 * buttonHeight);
}



//displayed at the top of the start screen.
function gameInstructions() {
  let instructions = [""
    ,"To Play: \n\n"
    ,"Choose a level and press the SPACE BAR to begin. \n"
    ,"The computer will display a random pattern of squares lighting up. \n"
    ,"Your goal is to remember the order and click the corresponding squares afterwards."
  ].join("");

  textStyle(BOLD);
  textSize(20);
  textAlign(CENTER);
  text(instructions, width / 2, 80);
}



//the layout of the screen and the squares at the beginning of both levels before
//the user clicks the space bar to begin.
function playMode() {
  background(0);

  let squareNumber = 0;

  for (let i = width / 2 - 100; i < (width / 2) + 30; i += 120) {
    for (let j = height / 2 - 100; j < (height / 2) + 30; j += 120) {
      fill(blockColours[squareNumber][0], blockColours[squareNumber][1], blockColours[squareNumber][2]);
      rect(i, j, 100, 100);
      squareNumber += 1;
    }
  }
}



//a button which returns to the start screen when clicked.
function returnToStart() {
  let buttonWidth = 100;
  let buttonHeight = 30;
  let leftSide = width - (buttonWidth + 30);
  let topSide = 30 - buttonHeight / 2;
  let rightSide = leftSide + buttonWidth;
  let bottomSide = topSide + buttonHeight;

  fill(204, 102, 153);
  if (mouseX >= leftSide && mouseX <= rightSide && mouseY >= topSide && mouseY <= bottomSide) {
    fill(223, 159, 191);
    if (mouseIsPressed) {
      popSound.play();
      state = 1;
      orderCounter = 0;
      arrayCounter = -1;
      runOrder = false;
    }
  }

  noStroke();
  rect(leftSide, topSide, buttonWidth, buttonHeight);

  textStyle(BOLD);
  textSize(16);
  textAlign(CENTER, CENTER);
  fill(0);
  text("Return", leftSide + 0.5 * buttonWidth, topSide + 0.5 * buttonHeight);
}


//displays the computer selected order of colours when the space bar is pressed.
function keyPressed() {
  if (key === " ") {
    runOrder = true;
    return false;
  }
}



//takes in the array generated by the computer to determine the order of colours,
//and then displays the corresponding squares for one second each. Once it has
//cycled through all of the values, it allows the user to respond.
function squareOrderFxn (array) {

  if (orderCounter % 60 === 0) {
    arrayCounter += 1;
  }

  if (array[arrayCounter] === 1) {
    //red tint
    fill(255, 179, 179);
    rect(width/2 - 100, height/2 - 100, 100, 100);
  }

  else if (array[arrayCounter] === 2) {
    //green tint
    fill(179, 255, 179);
    rect(width/2 - 100, height/2 + 20, 100, 100);
  }

  else if (array[arrayCounter] === 3) {
    //blue tint
    fill(179, 179, 255);
    rect(width/2 + 20, height/2 - 100, 100, 100);
  }

  else if (array[arrayCounter] === 4) {
    //yellow tint
    fill(255, 255, 204);
    rect(width/2 + 20, height/2 + 20, 100, 100);
  }

  if (arrayCounter < array.length) {
    orderCounter += 1;
  }

  else {
    userTry = true;
  }
}



//tints the squares when the mouse hovers overtop and keeps track of the squares
//the user has clicked. If a square is clicked, it sends a value between 1 and 4
//to a new array depending on the square.
function userSelection (userArray) {
  if (mouseX >= (width/2 - 100) && mouseX <= width/2) {
    if (mouseY >= (height/2 - 100) && mouseY <= height/2) {
      fill(255, 179, 179); //red tint
      rect(width/2 - 100, height/2 - 100, 100, 100);
      if (mouseIsPressed) {
        popSound.play();
        userArray.push(1);
        mouseIsPressed = false;
      }
    }
  }

  if (mouseX >= (width/2 - 100) && mouseX <= width/2) {
    if (mouseY >= (height/2 + 20) && mouseY <= height/2 + 120) {
      fill(179, 255, 179); //green tint
      rect(width/2 - 100, height/2 + 20, 100, 100);
      if (mouseIsPressed) {
        popSound.play();
        userArray.push(2);
        mouseIsPressed = false;
      }
    }
  }

  if (mouseX >= (width/2 + 20) && mouseX <= width/2 + 120) {
    if (mouseY >= (height/2 - 100) && mouseY <= height/2) {
      fill(179, 179, 255); //blue tint
      rect(width/2 + 20, height/2 - 100, 100, 100);
      if (mouseIsPressed) {
        popSound.play();
        userArray.push(3);
        mouseIsPressed = false;
      }
    }
  }

  if (mouseX >= (width/2 + 20) && mouseX <= width/2 + 120) {
    if (mouseY >= (height/2 + 20) && mouseY <= height/2 + 120) {
      fill(255, 255, 204); //yellow tint
      rect(width/2 + 20, height/2 + 20, 100, 100);
      if (mouseIsPressed) {
        popSound.play();
        userArray.push(4);
        mouseIsPressed = false;
      }
    }
  }

  //once the array containing the user's choices becomes the same length as the
  //original array, the computer will check to see if the two arrays match.
  if (userArray.length === squareOrder.length) {
    checkAnswer = true;
    userTry = false;
  }
}



//determines whether the user is correct by comparing each value of the user's array
//with the original. If they are the same, the screen displays "Correct!", and if
//they are not, the screen displays "Nope!".
function isUserCorrect (computerArray, userArray) {
  for (let i = 0; i < computerArray.length; i++) {
    if (!(computerArray[i] === userArray[i])) {
      match = false;
    }
  }

  textSize(30);
  fill(255);
  textAlign(CENTER, CENTER);

  if (match) {
    text("Correct!", width/2 + 10, height/5);
  }
  else {
    text("Nope!", width/2 + 10, height/5);
  }
}
